[Interface]
# Key for cornbypass
# Bouncing = 9
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = The_Empire_Strikes_Back
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-CA#58
PublicKey = Revenge_Of_The_Sith
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.127.185.222:51820
