[Interface]
# Key for cornbypass
# Bouncing = 9
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
VPN Accelerator = on
PrivateKey = AB6ANOzC5TuP1NhT/pQecnTjk0pH1IRdswYR70CsIkg=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-CA#58
PublicKey = xRu4XSIeCCNh4wQqit2w0PwAqzAs7JVA4zQqxGOhSSY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.127.185.222:51820
