[Interface]
# Key for newcornbypass
# Bouncing = 8
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 8Fb7nUjakODRD+ut3w6V4HZJqiTUxKykOpd3RzLmam0=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-IL#436
PublicKey = Gme1WiCEJZZusmIlg1aqItLaxDhdMl51xypUy43oMmc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 154.47.25.206:51820