## Keybinds ##
bind = SUPER CTRL, L, exec , omarchy-lock-screen
bindd = SUPER CTRL SHIFT, V, VPN Toggle, exec, omarchy-toggle-vpn
bindd = SUPER CTRL, 3, Screenshot fullscreen to clipboard, exec, omarchy-cmd-screenshot smart clipboard
bindd = SUPER CTRL, 4, Screenshot area with editing, exec, omarchy-cmd-screenshot
bindd = SUPER CTRL, 5, Screenshot fullscreen to file, exec, omarchy-cmd-screenshot smart

# bind = $mainMod shift, left, resizeactive, -10 0
# bind = $mainMod shift, right, resizeactive, 10 0
# bind = $mainMod shift, up, resizeactive, 0 -10
# bind = $mainMod shift, down, resizeactive, 0 10

## Input changes ##
# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = us
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }

  follow_mouse = 0
  natural_scroll = true
}

# Scroll nicely in the terminal
# windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
# windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

decoration {
    active_opacity = 0.8
    inactive_opacity = 0.8
    dim_inactive = false
  }

exec-once = hyprdynamicmonitors run

$terminal = kitty
$browser = zen_browser
