# Full documentation https://wiki.hyprland.org

source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animations.conf
