# Start Listeners
# exec-once=~/.config/ml4w/listeners.sh --startall

# Execute your favorite apps at launch
# exec-once = ~/.config/waybar/launch.sh # waybar
exec-once = hyprpaper
exec-once = dunst
exec-once = hypridle

# Load udiskie for automount external drives
exec-once = udiskie

# Load GTK settings
exec-once = ~/.config/hypr/scripts/gtk.sh

exec-once = hyprctl setcursor Bibata-Modern-Ice 24

